
# EN
ron.menu.ron_settings=RON Responsive System
ron.menu.settings=Settings
ron.menu.settings.enabled=Enabled
ron.menu.settings.complete_voicelines=Enable Complete Voicelines
ron.menu.toc_vo=TOC VO
ron.menu.officer_vo=Officer VO
